version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
      time: "00:00"
    commit-message:
      prefix: "perf"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    directory: "/packages/web"
    schedule:
      interval: "daily"
      time: "00:00"
    commit-message:
      prefix: "perf"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 0
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    commit-message:
      prefix: "perf"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    commit-message:
      prefix: "perf"
      prefix-development: "chore"
      include: "scope"
    versioning-strategy: increase
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    commit-message:
      prefix: "perf"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 0
