design:
  - design/**
github:
  - .github/**
infrastructure:
  - infrastructure/**
packages/common:
  - packages/@types/**
  - packages/common/**
packages/functions:
  - packages/@types/**
  - packages/common/**
  - packages/functions/**
packages/pioneer:
  - packages/pioneer/**
packages/types:
  - packages/@types/**
packages/typedoc:
  - packages/typedoc/**
packages/ui:
  - packages/@types/**
  - packages/common/**
  - packages/ui/**
packages/video:
  - packages/@types/**
  - packages/common/**
  - packages/video/**
packages/web:
  - packages/@types/**
  - packages/common/**
  - packages/ui/**
  - packages/video/**
  - packages/web/**
