- name: "backend"
  color: "0075ca"
  description: ""
- name: "bug"
  color: "d73a4a"
  description: ""
- name: "Epic"
  color: "3E4B9E"
  description: ""
- name: "frontend"
  color: "a2eeef"
  description: ""
- name: "infrastructure"
  color: "008672"
  description: ""
- name: "good-first-issue"
  color: "7057ff"
  description: ""
- name: "ready-to-merge"
  color: "d876e3"
  description: ""
- name: "roadmap"
  color: "0088CC"
  description: ""
- name: "day:early"
  color: "E98980"
  description: ""
- name: "day:middle"
  color: "F4B9B8"
  description: ""
- name: "day:late"
  color: "EBBBB0"
  description: ""
- name: "week:early"
  color: "44FFD2"
  description: ""
- name: "week:middle"
  color: "87F6FF"
  description: ""
- name: "week:late"
  color: "DAF5FF"
  description: ""
- name: "month:early"
  color: "B4F5F0"
  description: ""
- name: "month:middle"
  color: "2CEEF0"
  description: ""
- name: "month:late"
  color: "0476D0"
  description: ""
- name: "packages/common"
  color: "0366d6"
  description: ""
- name: "packages/pioneer"
  color: "0366d6"
  description: ""
- name: "packages/types"
  color: "0366d6"
  description: ""
- name: "packages/typedoc"
  color: "0366d6"
  description: ""
- name: "packages/ui"
  color: "0366d6"
  description: ""
- name: "packages/video"
  color: "0366d6"
  description: ""
- name: "packages/web"
  color: "0366d6"
  description: ""
