- name: "backend"
  color: "0075ca"
  description: ""
- name: "bug"
  color: "d73a4a"
  description: ""
- name: "Epic"
  color: "3E4B9E"
  description: ""
- name: "frontend"
  color: "a2eeef"
  description: ""
- name: "infrastructure"
  color: "008672"
  description: ""
- name: "good-first-issue"
  color: "7057ff"
  description: ""
- name: "ready-to-merge"
  color: "d876e3"
  description: ""
- name: "sprint:early"
  color: "44FFD2"
  description: ""
- name: "sprint:middle"
  color: "87F6FF"
  description: ""
- name: "sprint:late"
  color: "DAF5FF"
  description: ""
- name: "packages/common"
  color: "0366d6"
  description: ""
- name: "packages/pioneer"
  color: "0366d6"
  description: ""
- name: "packages/types"
  color: "0366d6"
  description: ""
- name: "packages/typedoc"
  color: "0366d6"
  description: ""
- name: "packages/ui"
  color: "0366d6"
  description: ""
- name: "packages/video"
  color: "0366d6"
  description: ""
- name: "packages/web"
  color: "0366d6"
  description: ""
