name: Deploy
on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  pioneer:
    if: github.actor == 'sentrei-bot'
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ env.BRANCH_NAME }}
          target_url: https://pioneer.sentrei.com
          environment: "Pioneer ${{ env.BRANCH_NAME }}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          submodules: true
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.4.0"
      - uses: actions/cache@v2.1.1
        with:
          path: |
            **/node_modules
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - working-directory: packages/pioneer
        run: |
          yarn run pioneer
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          target_url: https://pioneer.sentrei.com
      - if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          target_url: https://pioneer.sentrei.com
  typedoc:
    if: github.actor == 'sentrei-bot'
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ env.BRANCH_NAME }}
          target_url: https://${{ env.BRANCH_NAME }} .typedoc.sentrei.com
          environment: "Typedoc ${{ env.BRANCH_NAME }} "
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          submodules: true
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.4.0"
      - uses: actions/cache@v2.1.1
        with:
          path: |
            **/node_modules
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - working-directory: packages/typedoc
        run: |
          yarn run ${{ env.BRANCH_NAME }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          target_url: https://${{ env.BRANCH_NAME }} .typedoc.sentrei.com
      - if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          target_url: https://${{ env.BRANCH_NAME }} .typedoc.sentrei.com
