name: Sync
on:
  repository_dispatch:
    types: [sync-cmd]
  schedule:
    - cron: "0 0,8,16 * * *"
jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        branch: [alpha, beta, cla]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - run: |
          git config --local user.name 'sentrei-bot'
          git config --local user.email '70007101+sentrei-bot@users.noreply.github.com'
          git fetch --quiet && git merge --ff-only origin/main && git push || true
