name: UI
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
    paths:
      - "package.json"
      - "tsconfig.json"
      - "yarn.lock"
      - ".github/workflows/ui.yml"
      - "packages/@types/**"
      - "packages/common/**"
      - "packages/ui/**"
jobs:
  ui:
    if: github.actor == 'sentrei-bot' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.4.0"
      - uses: actions/cache@v2.1.1
        with:
          path: |
            **/node_modules
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run typescript
      - working-directory: packages/ui
        run: |
          yarn run test
      - uses: codecov/codecov-action@v1.0.13
        continue-on-error: true
        timeout-minutes: 3
        with:
          file: packages/ui/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: ui
      - working-directory: packages/ui
        run: |
          yarn run build
      - uses: chromaui/action@v1
        continue-on-error: true
        timeout-minutes: 3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: "packages/ui/out"
        env:
          CHROMATIC_STORYBOOK_VERSION: react@6.0.22
