name: Vercel
on: push
jobs:
  vercel:
    if: github.actor == 'sentrei-bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrnorm/deployment-action@releases/v1
        id: production
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.branch }}
          target_url: https://sentrei.com
          environment: "Vercel production"
      - timeout-minutes: 300
        uses: amondnet/vercel-action@v19.0.1+3
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
      - if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "success"
          deployment_id: ${{ steps.production.outputs.deployment_id }}
          target_url: https://sentrei.com
      - if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "failure"
          deployment_id: ${{ steps.production.outputs.deployment_id }}
          target_url: https://sentrei.com
