name: Vercel
on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  vercel:
    if: github.actor == 'sentrei-bot'
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.4.0"
      - uses: actions/cache@v2.1.1
        with:
          path: |
            **/node_modules
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run typescript
      - if: github.ref == 'refs/heads/main'
        uses: chrnorm/deployment-action@releases/v1
        id: production
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.branch }}
          target_url: https://sentrei.com
          environment: "Vercel production main"
      - if: github.ref == 'refs/heads/main'
        timeout-minutes: 300
        uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
      - if: success() && github.ref == 'refs/heads/main'
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "success"
          deployment_id: ${{ steps.production.outputs.deployment_id }}
          target_url: https://sentrei.com
      - if: failure() && github.ref == 'refs/heads/main'
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "failure"
          deployment_id: ${{ steps.production.outputs.deployment_id }}
          target_url: https://sentrei.com
      - if: github.ref != 'refs/heads/main'
        uses: chrnorm/deployment-action@releases/v1
        id: preview
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.branch }}
          target_url: https://${{ env.BRANCH_NAME }}.sentrei.com
          environment: "Vercel preview ${{ env.BRANCH_NAME }}"
      - if: github.ref != 'refs/heads/main'
        timeout-minutes: 300
        uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: |
            ${{ env.BRANCH_NAME }}.sentrei.com
      - if: success() && github.ref != 'refs/heads/main'
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "success"
          deployment_id: ${{ steps.preview.outputs.deployment_id }}
          target_url: https://${{ env.BRANCH_NAME }}.sentrei.com
      - if: failure() && github.ref != 'refs/heads/main'
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          state: "failure"
          deployment_id: ${{ steps.preview.outputs.deployment_id }}
          target_url: https://${{ env.BRANCH_NAME }}.sentrei.com
